[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
base_sepolia = "${RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
